name: curator
description: Curate your content.

publish_to: 'none'

version: 0.9.0+2

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # utilities

  webfeed: ^0.6.0
  sqflite: ^1.3.2+2
  path: ^1.6.4
  http: ^0.12.1
  url_launcher: ^5.5.0
  vibration: ^1.4.0
  shared_preferences: ^0.5.8
  opmlparser: ^0.1.0
  file_picker: 2.0.0

  # audio
  
  audio_service: ^0.16.1
  just_audio: ^0.6.5

  # State Management

  provider: ^4.3.1

  # widgets

  bottom_navy_bar: ^5.5.0
  flutter_html: ^1.0.0-pre.1
  flutter_speed_dial: ^1.2.5
  html_main_element: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  build_runner: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  fonts:
    - family: CustomIcons
      fonts:
       - asset: assets/CustomIcons.ttf

  uses-material-design: true

  assets:
    - "assets/opml_icon.png"
